src/Entity/Pets.php
<?php

namespace App\Entity;

use App\Repository\PetsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PetsRepository::class)]
class Pets
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $PetName = null;

    #[ORM\Column(length: 255)]
    private ?string $Age = null;

    #[ORM\Column(length: 255)]
    private ?string $Price = null;

    #[ORM\Column(length: 255)]
    private ?string $Sex = null;

    #[ORM\Column(length: 255)]
    private ?string $Image = null;

    #[ORM\ManyToOne(inversedBy: 'Pets')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $Category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPetName(): ?string
    {
        return $this->PetName;
    }

    public function setPetName(?string $PetName): static
    {
        $this->PetName = $PetName;

        return $this;
    }

    public function getAge(): ?string
    {
        return $this->Age;
    }

    public function setAge(string $Age): static
    {
        $this->Age = $Age;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->Price;
    }

    public function setPrice(string $Price): static
    {
        $this->Price = $Price;

        return $this;
    }

    public function getSex(): ?string
    {
        return $this->Sex;
    }

    public function setSex(string $Sex): static
    {
        $this->Sex = $Sex;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): static
    {
        $this->Image = $Image;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): static
    {
        $this->Category = $Category;

        return $this;
    }
}

src/Form/PetType.php
<?php

namespace App\Form;

use App\Entity\Pets;
use App\Entity\Category;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;


class PetType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('category',EntityType::class,array('class'=>'App\Entity\Category','choice_label'=>"cateName")
            )
            ->add('PetName',TextareaType::class)
            ->add('Age',TextType::class)
            ->add('Price',TextType::class)
            ->add('Sex',TextType::class)
            ->add('Image',FileType::class,[
                'label'=>'Image file',
                'mapped'=> false,
                'required'=>false,
                'constraints'=>[
                    new File ([
                        'maxSize'=> '1024k',
                        'mimeTypesMessage'=>'Please upload a valid image',
                    ])
                ]
            ])
            ->add('Category',EntityType::class,array('class'=>'App\Entity\Category','choice_label'=>'CateName'))
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Pets::class,
        ]);
    }
}

src/Controller/PetsController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Pets;
use App\Entity\Product;
use App\Form\PetType;
use App\Form\ProductType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use function Symfony\Bundle\MakerBundle\Util\findAllNodes;
use function Symfony\Config\Monolog\persistent;

class PetsController extends AbstractController
{
    #[Route('/', name: 'app_pets')]
    public function index(ManagerRegistry $doctrine): Response
    {
        $pet = $doctrine ->getRepository ('App\Entity\Pets')->findAll();
        return $this->render('pets/index.html.twig', [
            'pet'=> $pet
        ]);
    }

    #[Route('/pets/details/{id}', name:'app_PetsDetails')]
    public function detailAction(ManagerRegistry $doctrine, $id): Response
    {
        $pet = $doctrine ->getRepository ('App\Entity\Pets')->find($id);
        $category = $doctrine->getRepository(Category::class)->findAll();
        return $this->render('pets/details.html.twig', [
            'pet'=> $pet,
            'category' => $category
        ]);
    }

    #Route('/pets/delete/{id}', name: 'app_petsDelete')]
    public function deleteAction(ManagerRegistry $doctrine, $id): Response
    {
        $em = $doctrine -> getManager();
        $pet = $doctrine ->getRepository ('App\Entity\Pets')->find($id);
        $em ->remove($pet);
        $em -> flush();

        $this -> addFlash
        (
            'error',
        'Pets deleted'
        );
        return $this-> redirectToRoute('pets_list');

    }

    #[Route('/pets/create', name: 'app_petsCreate')]
    public function createAction(ManagerRegistry $doctrine, Request $request, SluggerInterface $slugger): Response
    {
        $pet = new Pets();
        $form = $this->createForm(PetType::class,$pet);
        $form -> handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // uplpad file
            $productImage = $form->get('Image')->getData();
            if ($productImage) {
                $originalFilename = pathinfo($productImage->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $productImage->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $productImage->move(
                        $this->getParameter('productImages_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    $this->addFlash(
                        'error',
                        'Cannot upload'
                    );// ... handle exception if something happens during file upload
                }
                $pet->setImage($newFilename);
            }else{
                $this->addFlash(
                    'error',
                    'Cannot upload'
                );// ... handle exception if something happens during file upload
            }
            $em = $doctrine->getManager();
            $em->persist($pet);
            $em->flush();

            $this->addFlash(
                'notice',
                'Product Added'
            );
            return $this->redirectToRoute('app_pets');
        }
        return $this-> renderForm ('pets/create.html.twig', ['form'=> $form]);
    }

    #[Route('/pets/edit/{id}', name: 'app_petsEdit')]
    public function editAction(ManagerRegistry $doctrine, Request $request, SluggerInterface $slugger, int $id): Response
    {
        $entityManager = $doctrine->getManager();
        $pet = $entityManager->getRepository(Pets::class)->find($id);
        $form = $this->createForm(PetType::class, @$pet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // uplpad file
            $productImage = $form->get('Image')->getData();
            if ($productImage) {
                $originalFilename = pathinfo($productImage->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $productImage->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $productImage->move(
                        $this->getParameter('productImages_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    $this->addFlash(
                        'error',
                        'Cannot upload'
                    );// ... handle exception if something happens during file upload
                }
                $pet->setImage($newFilename);
            }else{
                $this->addFlash(
                    'error',
                    'Cannot upload'
                );// ... handle exception if something happens during file upload
            }
            $em = $doctrine->getManager();
            $em->persist($pet);
            $em->flush();

            $this->addFlash(
                'notice',
                'Product Added'
            );
            return $this->redirectToRoute('app_pets');
        }
        return $this-> renderForm ('pets/edit.html.twig', ['form'=> $form]);
    }



}

templates/pets/create.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {{ form_start(form) }}
    <div class="form-group">
        <label for="category">Category</label>
        {{ form_widget(form.category,{
            'attr':{
                'class':'form-control'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="category">Product Name:</label>
        {{ form_widget(form.PetName,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Product name'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="category">Price:</label>
        {{ form_widget(form.Price,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Price'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="description">Sex</label>
        {{ form_widget(form.Sex,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Description'
            }
        }) }}
    </div>

    <div class="form-group">
        <label for="due_date">Age</label>
        {{ form_widget(form.Age,{
            'attr':{
                'class':'form-control'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="due_date">Image</label>
        {{ form_widget(form.Image,{

        }) }}
    </div>
    <input type="submit" name="app_petsCreate" value="Create" class="btn btn-primary"/>
    {{ form_end(form) }}
{% endblock %}


templates/pets/details.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <br><br><br><br>
<a href="{{ path('app_pets') }}" class="btn btn-default">Back to Product List</a>
<hr/>

    <div class="container" >
        <div class="row" style="background: #eaeaea; border-radius: 10px">
            <div class="col-2" style="padding: 10px">
                <img src="{{ asset('upload/productImages/' ~ pet.Image) }}" class="img-fluid" alt=""/>
            </div>
            <div class="col-9" style="padding: 10px">
                <h2 class="page-header">{{ pet.petName }}</h2>
                <p style="color: red"><b>{{ pet.price }}đ</b></p>
                <p>Age: {{ pet.age }}</p>
                <p>Sex: {{ pet.sex }}</p>
                <div>
                    <a href="{{ path('app_petsEdit', {'id': pet.id}) }} " class='btn btn-edit'>Edit</a>
                    <a href="{{ path('app_petsDelete', {'id': pet.id}) }} "class='btn btn-danger'>Delete</a>
                </div>
            </div>
        </div>
    </div><br><br>

    <style>
        .btn-edit{
            border-color: green;
            color: green;
        }
        .btn-edit:hover{
            background: green;
            color: white;
        }
    </style>
{% endblock %}

templates/pets/edit.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {{ form_start(form) }}
    <div class="form-group">
        <label for="category">Category</label>
        {{ form_widget(form.category,{
            'attr':{
                'class':'form-control'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="category">Product Name:</label>
        {{ form_widget(form.PetName,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Product name'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="category">Price:</label>
        {{ form_widget(form.Price,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Price'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="description">Sex</label>
        {{ form_widget(form.Sex,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Description'
            }
        }) }}
    </div>

    <div class="form-group">
        <label for="due_date">Age</label>
        {{ form_widget(form.Age,{
            'attr':{
                'class':'form-control'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="due_date">Image</label>
        {{ form_widget(form.Image,{

        }) }}
    </div>
    <input type="submit" name="app_petsEdit" value="Edit" class="btn btn-primary"/>
    {{ form_end(form) }}
{% endblock %}


templates/pets/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <section id="hero">
        <div id="heroCarousel" data-bs-interval="5000" class="carousel slide carousel-fade" data-bs-ride="carousel">

            <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

            <div class="carousel-inner" role="listbox">

                <!-- Slide 1 -->
                <div class="carousel-item active" style="background-image: url(/assets/img/slide/1.jpg);"></div>

                <!-- Slide 2 -->
                <div class="carousel-item" style="background-image: url(/assets/img/slide/2.jpg);"></div>

                <!-- Slide 3 -->
                <div class="carousel-item" style="background-image: url(/assets/img/slide/3.jpg);"></div>

            </div>

            <a class="carousel-control-prev" href="#heroCarousel" role="button" data-bs-slide="prev">
                <span class="carousel-control-prev-icon bi bi-chevron-left" aria-hidden="true"></span>
            </a>

            <a class="carousel-control-next" href="#heroCarousel" role="button" data-bs-slide="next">
                <span class="carousel-control-next-icon bi bi-chevron-right" aria-hidden="true"></span>
            </a>

        </div>
    </section><!-- End Hero -->
<div class="bs-example" data-example-id="striped-table">
    <h2 style="text-align: center;padding: 10px">Thú Cưng</h2>
    <div class="row portfolio-container">
        {% for pets in pet %}
            <div class="col-lg-4 col-md-6 portfolio-item filter-app" style="padding: 20px">
                <div class="portfolio-wrap" style="width: 250px">
                    <a href="{{path('app_PetsDetails',{'id':pets.id})}} ">
                    <div style="height: 350px;">
                    <img src="{{ asset('upload/productImages/' ~ pets.Image) }}"  style="width: 100%" class="img-fluid" alt=""/>
                    </div>
                    <div class="portfolio-info">
                        <h4>{{ pets.PetName }}</h4>
                        <p>{{ pets.Price }}</p>
                    </div>
                </a>
                </div>
            </div>


        {% endfor %}
    </div>
</div><br><br>
{% endblock %}