src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $CateName = null;

    #[ORM\OneToMany(mappedBy: 'Category', targetEntity: Pets::class)]
    private Collection $Pets;

    public function __construct()
    {
        $this->Pets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCateName(): ?string
    {
        return $this->CateName;
    }

    public function setCateName(?string $CateName): static
    {
        $this->CateName = $CateName;

        return $this;
    }

    /**
     * @return Collection<int, Pets>
     */
    public function getPets(): Collection
    {
        return $this->Pets;
    }

    public function addPet(Pets $pet): static
    {
        if (!$this->Pets->contains($pet)) {
            $this->Pets->add($pet);
            $pet->setCategory($this);
        }

        return $this;
    }

    public function removePet(Pets $pet): static
    {
        if ($this->Pets->removeElement($pet)) {
            // set the owning side to null (unless already changed)
            if ($pet->getCategory() === $this) {
                $pet->setCategory(null);
            }
        }

        return $this;
    }
}

src/Form/CategoryType.php
<?php

namespace App\Form;

use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('CatName')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Category::class,
        ]);
    }
}

src/Controller/CategoryController.php
<?php

namespace App\Controller;

use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CategoryController extends AbstractController
{
    #[Route('/category', name: 'app_category')]
    public function index(ManagerRegistry $doctrine): Response
    {
        $categories= $doctrine ->getRepository ('App\Entity\Category')->findAll();
        return $this->render('category/index.html.twig', [
            'categories' => $categories,
        ]);
    }
}

templates/category/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="bs-example" data-example-id="striped-table">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Category</th>

            </tr>
            </thead>
            <tbody>
            {% for category in categories %}
                <tr>
                    <th scope="row">{{ category.id }}</th>
                    <td><a href="{{path('app_category',{'id':category.id})}} ">{{ category.cateName }}</a></td>
{#                    <td>#}
{#                        <a href="{{path('app_category',{'id':category.id})}} " class='btn btn-success'>View</a>#}
{#                        <a href="#" class='btn btn-default'>Edit</a>#}
{#                        <a href="{{ path('product_delete', {'id': category.id}) }} "class='btn btn-danger'>Delete</a>#}
{#                    </td>#}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}